version: '3.1'
services:
  admin:
    image: ./admin
    restart: always
    volumes:
      - ./storage:/home/storage
    ports:
      - 3000:3000
  mongo:
    image: mongo:4.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
  mysql:
    image: mariadb:10.3.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql